# County Health Trends (2019–2023)
## ADS-508 Final Project – Data Cleaning and Exploration

## 1. Setup: Libraries and Tools
We begin by importing libraries for data loading, cloud storage, and data exploration.

In [26]:
!pip install httpimport

Requirement already satisfied: httpimport in /opt/conda/lib/python3.11/site-packages (1.4.1)

In [27]:
import pandas as pd
import boto3 
import httpimport 
import io

## 2. Load and Combine Multi-Year Datasets
We load public health datasets from 2019–2023 and combine them into one DataFrame for analysis.

In [28]:
# Define file paths for all datasets
files = [
    "/home/sagemaker-user/ADS-508-team-project/datasets/analytic_data2019.csv",
    "/home/sagemaker-user/ADS-508-team-project/datasets/analytic_data2020_0.csv",
    "/home/sagemaker-user/ADS-508-team-project/datasets/analytic_data2021.csv",
    "/home/sagemaker-user/ADS-508-team-project/datasets/analytic_data2022.csv",
    "/home/sagemaker-user/ADS-508-team-project/datasets/analytic_data2023_0.csv"
]

# Define a function to load and clean the dataset
def load_and_clean_csv(file):
    df = pd.read_csv(file, header=0, low_memory=False)
    df = df.drop(index=0).reset_index(drop=True)
    df.columns = df.columns.str.strip().str.lower()
    return df

# Apply the function to all files
df_list = [load_and_clean_csv(file) for file in files]

# Merge all datasets
df_combined = pd.concat(df_list, ignore_index=True)

## 3. Select Relevant Features & Renamed Columns

In [71]:
# Select Relevant Columns
selected_columns = [
   'release year', 'state abbreviation', 'name',
    'premature death raw value', 'poor or fair health raw value', 'adult smoking raw value',
    'adult obesity raw value', 'physical inactivity raw value', 'access to exercise opportunities raw value',
    'flu vaccinations raw value', 'mammography screening raw value', 'uninsured raw value',
    'driving alone to work raw value', 'long commute - driving alone raw value',
    'severe housing problems raw value', 'air pollution - particulate matter raw value',
    'drinking water violations raw value', 'children in poverty raw value', 'income inequality raw value',
    'social associations raw value', 'homeownership raw value', 'median household income raw value',
    'population raw value'
]

#Use selected columns and rename them
df_final = df_combined[selected_columns]

rename_dict = {
    'release year': 'year',
    'state abbreviation': 'state',
    'name': 'county',
    'premature death raw value': 'premature_death',
    'poor or fair health raw value': 'poor_fair_health',
    'adult smoking raw value': 'adult_smoking',
    'adult obesity raw value': 'obesity_rate',
    'physical inactivity raw value': 'physical_inactivity',
    'access to exercise opportunities raw value': 'access_exercise',
    'flu vaccinations raw value': 'flu_vaccination_rate',
    'mammography screening raw value': 'mammography_screening',
    'uninsured raw value': 'uninsured_rate',
    'driving alone to work raw value': 'driving_alone_to_work',
    'long commute - driving alone raw value': 'long_commute',
    'severe housing problems raw value': 'severe_housing_problems',
    'air pollution - particulate matter raw value': 'air_pollution_pmatter',
    'drinking water violations raw value': 'drinking_water_violations',
    'children in poverty raw value': 'children_in_poverty',
    'income inequality raw value': 'income_inequality',
    'social associations raw value': 'social_associations',
    'homeownership raw value': 'homeownership',
    'median household income raw value': 'median_household_income',
    'population raw value': 'population'
}

df_final= df_final.rename(columns=rename_dict)


print(df_final.head())

   year state          county premature_death poor_fair_health adult_smoking  \
0  2019    US   United States     6900.630354              NaN           NaN
1  2019    AL         Alabama    9917.2328984     0.2140240566   0.215381544
2  2019    AL  Autauga County    8824.0571232     0.1841112436   0.191246585
3  2019    AL  Baldwin County    7224.6321603     0.1806045782  0.1679548515
4  2019    AL  Barbour County     9586.165037     0.2577341563  0.2154087757

  obesity_rate physical_inactivity access_exercise flu_vaccination_rate  ...  \
0        0.285               0.222    0.8389448174                  NaN  ...
1        0.351               0.282    0.6164961831                 0.42  ...
2        0.375               0.311     0.686775027                 0.41  ...
3         0.31               0.238    0.7197103119                 0.45  ...
4        0.443               0.282    0.5362566923                 0.37  ...

  long_commute severe_housing_problems air_pollution_pmatter  \
0        0.352            0.1837308951                   NaN
1        0.337            0.1491215019                    11
2        0.383            0.1495464575                  11.7
3        0.405            0.1383172525                  10.3
4        0.338            0.1545553145                  11.5

  drinking_water_violations children_in_poverty income_inequality  \
0                       NaN               0.184      4.9414857531
1              0.0746268657               0.244       5.238579235
2                         0               0.193      4.6366638778
3                         1               0.147      4.5185596041
4                         0               0.503      5.7550626063

  social_associations homeownership median_household_income population
0        9.3003532014  0.6381868061                   60336  325719178
1        12.242715851  0.6857437544                   48193    4874747
2        12.631730908   0.732877363                   58343      55504
3        10.692212904  0.7285933826                   56607     212628
4        8.4729443482  0.6250680013                   32490      25270

[5 rows x 23 columns]

In [43]:
# Path in SageMaker
cleaned_file_path = "/home/sagemaker-user/ADS-508-team-project/datasets/analytic_data_2019_2023_cleaned.csv"

# Save the cleaned dataset
df_final.to_csv(cleaned_file_path, index=False)

## 4. Exploratory Data Analysis (EDA) 
We use the `jeda` library to generate quick insights and data quality checks. We also used imputation to fill missing values in continous features using the mean.

In [61]:
# Upload dataset to S3
s3 = boto3.client('s3')
bucket_name = 'jc-bucket-ads508-2025-finalproject'
s3_key = "datasets/analytic_data_2019_2023.csv"

s3.upload_file(cleaned_file_path, bucket_name, s3_key)

In [62]:
# import jcds 
with httpimport.github_repo('junclemente', 'jcds', ref='0.1.0'):
    import jcds.eda as jeda

In [63]:
# load dataset from s3 into dataframe
obj = s3.get_object(Bucket=bucket_name, Key=s3_key)
# read Excel file into dataframe
df = pd.read_csv(io.BytesIO(obj['Body'].read()))

print(df.head())

   year state          county  premature_death  poor_fair_health  \
0  2019    US   United States      6900.630354               NaN
1  2019    AL         Alabama      9917.232898          0.214024
2  2019    AL  Autauga County      8824.057123          0.184111
3  2019    AL  Baldwin County      7224.632160          0.180605
4  2019    AL  Barbour County      9586.165037          0.257734

   adult_smoking  obesity_rate  physical_inactivity  access_exercise  \
0            NaN         0.285                0.222         0.838945
1       0.215382         0.351                0.282         0.616496
2       0.191247         0.375                0.311         0.686775
3       0.167955         0.310                0.238         0.719710
4       0.215409         0.443                0.282         0.536257

   flu_vaccination_rate  ...  long_commute  severe_housing_problems  \
0                   NaN  ...         0.352                 0.183731
1                  0.42  ...         0.337                 0.149122
2                  0.41  ...         0.383                 0.149546
3                  0.45  ...         0.405                 0.138317
4                  0.37  ...         0.338                 0.154555

   air_pollution_pmatter  drinking_water_violations  children_in_poverty  \
0                    NaN                        NaN                0.184
1                   11.0                   0.074627                0.244
2                   11.7                   0.000000                0.193
3                   10.3                   1.000000                0.147
4                   11.5                   0.000000                0.503

   income_inequality  social_associations  homeownership  \
0           4.941486             9.300353       0.638187
1           5.238579            12.242716       0.685744
2           4.636664            12.631731       0.732877
3           4.518560            10.692213       0.728593
4           5.755063             8.472944       0.625068

   median_household_income  population
0                  60336.0   325719178
1                  48193.0     4874747
2                  58343.0       55504
3                  56607.0      212628
4                  32490.0       25270

[5 rows x 23 columns]

In [64]:
# verify that file exists in s3
response = s3.list_objects_v2(Bucket=bucket_name, Prefix = 'datasets/')
for obj in response.get('Contents', []):
    print(obj['Key'])

datasets/analytic_data_2019_2023.csv
datasets/analytic_data_2019_2023_cleaned.csv
datasets/employee_benefits.xlsx
datasets/employee_benefits_2010_2024.csv
datasets/employee_benefits_file_info.csv

In [65]:
jeda.quick_report(df)

============================================
Quick Report - info(memory_usage='deep')
Total cols: 23
Rows missing all values: 0 (0.0%)
Total Rows: 15970
Cols with missing values: 16 (69.57%)
Total missing values in dataset: 1069
============================================

In [66]:
jeda.long_report(df)

============================================
Quick Report - info(memory_usage='deep')
Total cols: 23
Rows missing all values: 0 (0.0%)
Total Rows: 15970
Cols with missing values: 16 (69.57%)
Total missing values in dataset: 1069
============================================
Categorical features: 2
- state: 52 unique values
- county: 1929 unique values
============================================
Continuous features: 21
- year: 5 unique values
- premature_death: 12533 unique values
- poor_fair_health: 9912 unique values
- adult_smoking: 9894 unique values
- obesity_rate: 378 unique values
- physical_inactivity: 379 unique values
- access_exercise: 11596 unique values
- flu_vaccination_rate: 70 unique values
- mammography_screening: 66 unique values
- uninsured_rate: 15929 unique values
- driving_alone_to_work: 15890 unique values
- long_commute: 691 unique values
- severe_housing_problems: 14578 unique values
- air_pollution_pmatter: 171 unique values
- drinking_water_violations: 186 unique values
- children_in_poverty: 509 unique values
- income_inequality: 15948 unique values
- social_associations: 14922 unique values
- homeownership: 15869 unique values
- median_household_income: 13424 unique values
- population: 14493 unique values

In [67]:
jeda.dqr_cont(df)

The non-categorical features are:
['year', 'premature_death', 'poor_fair_health', 'adult_smoking', 'obesity_rate', 'physical_inactivity', 'access_exercise', 'flu_vaccination_rate', 'mammography_screening', 'uninsured_rate', 'driving_alone_to_work', 'long_commute', 'severe_housing_problems', 'air_pollution_pmatter', 'drinking_water_violations', 'children_in_poverty', 'income_inequality', 'social_associations', 'homeownership', 'median_household_income', 'population']
Data Quality for Continous Features
Total Features: 21 / 15970 rows

                      Feature  Count  Missing  % missing  Cardinality
0                        year  15970        0       0.00            5
1             premature_death  15670      300       1.88        12533
2            poor_fair_health  15967        3       0.02         9912
3               adult_smoking  15967        3       0.02         9894
4                obesity_rate  15968        2       0.01          378
5         physical_inactivity  15968        2       0.01          379
6             access_exercise  15814      156       0.98        11596
7        flu_vaccination_rate  15880       90       0.56           70
8       mammography_screening  15870      100       0.63           66
9              uninsured_rate  15965        5       0.03        15929
10      driving_alone_to_work  15968        2       0.01        15890
11               long_commute  15969        1       0.01          691
12    severe_housing_problems  15970        0       0.00        14578
13      air_pollution_pmatter  15817      153       0.96          171
14  drinking_water_violations  15746      224       1.40          186
15        children_in_poverty  15965        5       0.03          509
16          income_inequality  15954       16       0.10        15948
17        social_associations  15970        0       0.00        14922
18              homeownership  15970        0       0.00        15869
19    median_household_income  15963        7       0.04        13424
20                 population  15970        0       0.00        14493

Descriptive Stats

,count,mean,std,min,25%,50%,75%,max
year,15970.0,2021.00,1.41,2019.00,2020.00,2021.00,2022.00,2.023000e+03
premature_death,15670.0,8647.89,2818.70,1625.72,6719.42,8298.15,10179.86,4.393907e+04
poor_fair_health,15967.0,0.18,0.05,0.06,0.15,0.18,0.22,4.500000e-01
adult_smoking,15967.0,0.19,0.04,0.06,0.16,0.19,0.22,4.500000e-01
obesity_rate,15968.0,0.34,0.05,0.11,0.31,0.34,0.38,5.900000e-01
physical_inactivity,15968.0,0.27,0.06,0.08,0.23,0.27,0.31,5.200000e-01
access_exercise,15814.0,0.61,0.24,0.00,0.47,0.64,0.79,1.000000e+00
flu_vaccination_rate,15880.0,0.43,0.10,0.02,0.37,0.44,0.50,7.100000e-01
mammography_screening,15870.0,0.40,0.08,0.03,0.35,0.40,0.45,6.900000e-01
uninsured_rate,15965.0,0.12,0.05,0.02,0.08,0.11,0.15,4.100000e-01
driving_alone_to_work,15968.0,0.79,0.08,0.05,0.77,0.81,0.84,9.900000e-01
long_commute,15969.0,0.32,0.13,0.00,0.22,0.31,0.41,8.400000e-01
severe_housing_problems,15970.0,0.14,0.05,0.00,0.11,0.13,0.16,7.100000e-01
air_pollution_pmatter,15817.0,8.24,1.92,0.90,7.00,8.40,9.50,2.090000e+01
drinking_water_violations,15746.0,0.37,0.48,0.00,0.00,0.00,1.00,1.000000e+00
children_in_poverty,15965.0,0.20,0.09,0.02,0.14,0.19,0.25,7.500000e-01
income_inequality,15954.0,4.52,0.78,1.05,4.00,4.40,4.89,1.197000e+01
social_associations,15970.0,11.92,6.17,0.00,8.30,11.21,14.67,7.062000e+01
homeownership,15970.0,0.72,0.08,0.00,0.68,0.73,0.77,9.700000e-01
median_household_income,15963.0,55354.49,14645.26,22679.00,45619.00,52942.00,62002.00,1.603050e+05
population,15970.0,308548.03,5943457.32,57.00,11086.25,26530.00,73461.50,3.318937e+08

In [68]:
# Fill missing values with mean for continous variables
df = df.fillna(df.mean(numeric_only=True))
jeda.dqr_cont(df)

The non-categorical features are:
['year', 'premature_death', 'poor_fair_health', 'adult_smoking', 'obesity_rate', 'physical_inactivity', 'access_exercise', 'flu_vaccination_rate', 'mammography_screening', 'uninsured_rate', 'driving_alone_to_work', 'long_commute', 'severe_housing_problems', 'air_pollution_pmatter', 'drinking_water_violations', 'children_in_poverty', 'income_inequality', 'social_associations', 'homeownership', 'median_household_income', 'population']
Data Quality for Continous Features
Total Features: 21 / 15970 rows

                      Feature  Count  Missing  % missing  Cardinality
0                        year  15970        0        0.0            5
1             premature_death  15970        0        0.0        12533
2            poor_fair_health  15970        0        0.0         9912
3               adult_smoking  15970        0        0.0         9894
4                obesity_rate  15970        0        0.0          378
5         physical_inactivity  15970        0        0.0          379
6             access_exercise  15970        0        0.0        11596
7        flu_vaccination_rate  15970        0        0.0           70
8       mammography_screening  15970        0        0.0           66
9              uninsured_rate  15970        0        0.0        15929
10      driving_alone_to_work  15970        0        0.0        15890
11               long_commute  15970        0        0.0          691
12    severe_housing_problems  15970        0        0.0        14578
13      air_pollution_pmatter  15970        0        0.0          171
14  drinking_water_violations  15970        0        0.0          186
15        children_in_poverty  15970        0        0.0          509
16          income_inequality  15970        0        0.0        15948
17        social_associations  15970        0        0.0        14922
18              homeownership  15970        0        0.0        15869
19    median_household_income  15970        0        0.0        13424
20                 population  15970        0        0.0        14493

Descriptive Stats

,count,mean,std,min,25%,50%,75%,max
year,15970.0,2021.00,1.41,2019.00,2020.00,2021.00,2022.00,2.023000e+03
premature_death,15970.0,8647.89,2792.10,1625.72,6755.35,8365.71,10142.19,4.393907e+04
poor_fair_health,15970.0,0.18,0.05,0.06,0.15,0.18,0.22,4.500000e-01
adult_smoking,15970.0,0.19,0.04,0.06,0.16,0.19,0.22,4.500000e-01
obesity_rate,15970.0,0.34,0.05,0.11,0.31,0.34,0.38,5.900000e-01
physical_inactivity,15970.0,0.27,0.06,0.08,0.23,0.27,0.31,5.200000e-01
access_exercise,15970.0,0.61,0.24,0.00,0.47,0.64,0.79,1.000000e+00
flu_vaccination_rate,15970.0,0.43,0.10,0.02,0.37,0.44,0.50,7.100000e-01
mammography_screening,15970.0,0.40,0.08,0.03,0.35,0.40,0.45,6.900000e-01
uninsured_rate,15970.0,0.12,0.05,0.02,0.08,0.11,0.15,4.100000e-01
driving_alone_to_work,15970.0,0.79,0.08,0.05,0.77,0.81,0.84,9.900000e-01
long_commute,15970.0,0.32,0.13,0.00,0.22,0.31,0.41,8.400000e-01
severe_housing_problems,15970.0,0.14,0.05,0.00,0.11,0.13,0.16,7.100000e-01
air_pollution_pmatter,15970.0,8.24,1.91,0.90,7.00,8.40,9.50,2.090000e+01
drinking_water_violations,15970.0,0.37,0.48,0.00,0.00,0.00,1.00,1.000000e+00
children_in_poverty,15970.0,0.20,0.09,0.02,0.14,0.19,0.25,7.500000e-01
income_inequality,15970.0,4.52,0.78,1.05,4.00,4.40,4.89,1.197000e+01
social_associations,15970.0,11.92,6.17,0.00,8.30,11.21,14.67,7.062000e+01
homeownership,15970.0,0.72,0.08,0.00,0.68,0.73,0.77,9.700000e-01
median_household_income,15970.0,55354.49,14642.05,22679.00,45624.50,52947.50,61996.50,1.603050e+05
population,15970.0,308548.03,5943457.32,57.00,11086.25,26530.00,73461.50,3.318937e+08

In [69]:
jeda.dqr_cat(df)

The categorical features are:
['state', 'county']
Data Quality Report for Categorical Features
Total features: 2 / 15970 rows
============================================
Stats
-----

  Feature  Count  Missing  % Missing  Cardinality
0   state  15970        0        0.0           52
1  county  15970        0        0.0         1929

Mode 1
------

  Feature             Mode 1  Mode 1 Freq.  Mode 1 %
0   state                 TX          1275      7.98
1  county  Washington County           150      0.94

Mode 2
------

  Feature            Mode 2  Mode 2 Freq.  Mode 2 %
0   state                GA           800      5.01
1  county  Jefferson County           125      0.78

Descriptive Stats
-----------------

        count unique                top  freq
state   15970     52                 TX  1275
county  15970   1929  Washington County   150

## 5. Save and Upload Cleaned Data to S3
We export the cleaned dataset and upload it to our S3 bucket for storage and future access.

In [70]:
# Save the cleaned dataframe to a local CSV file
df.to_csv("final_cleaned_data.csv", index=False)

# Upload the file to S3
s3.upload_file("final_cleaned_data.csv", bucket_name, "datasets/final_cleaned_data.csv")

print("✅ Cleaned data uploaded to S3!")

✅ Cleaned data uploaded to S3!